import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify';
import "../src/config/toastify"
import AuthContext from '@/src/config/AuthContext';
import Topbar from '@/components/topbar/topbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <AuthContext>
          <Topbar/>
        {children}
        </AuthContext>
        <ToastContainer/>
        {/* <Footer/> */}
        </body>
    </html>
  )
}
